In [1]:
import numpy as np
import pandas as pd
import re
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [2]:
df = pd.read_csv('houses.csv')
df.shape

(1044, 21)

In [3]:
df.sample(6)

,property_name,link,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
936,4 Bedroom House for sale in Sector 4 Gurgaon,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,2.35 Crore,"₹ 16,319/sq.ft.",(134 sq.m.) Plot Area,Plot area 160(133.78 sq.m.),4 Bedrooms,4 Bathrooms,2 Balconies,Pooja Room,"Sector 4 Gurgaon, Gurgaon, Haryana",2 Floors,East,10+ Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Kr D...",160 sq yd independent house 2 side open in sec...,"['3 Wardrobe', '5 Fan', '14 Light', 'No AC', '...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ...",S69966248
619,3 Bedroom House for sale in New Colony,https://www.99acres.com/3-bhk-bedroom-independ...,NaN,6.5 Crore,"₹ 15,046/sq.ft.",(401 sq.m.) Plot Area,Plot area 480(401.34 sq.m.),3 Bedrooms,2 Bathrooms,3+ Balconies,NaN,"New Colony, Gurgaon, Haryana",NaN,NaN,10+ Year Old,"['Geeta Nursing Home Gurgaon', 'Chiranjiv Hosp...",Old construction house in new colony gurgaon.,[],['Private Garden / Terrace'],"['Environment4 out of 5', 'Lifestyle4 out of 5...",V39950201
708,4 Bedroom House for sale in Sector 48 Gurgaon,https://www.99acres.com/4-bhk-bedroom-independ...,Vipul Tatvam Villa,7.35 Crore,"₹ 22,812/sq.ft.",(299 sq.m.) Plot Area,Plot area 358(299.33 sq.m.),4 Bedrooms,5 Bathrooms,2 Balconies,"Servant Room,Store Room,Study Room,Pooja Room","001, Sector 48 Gurgaon, Gurgaon, Haryana",2 Floors,South,5 to 10 Year Old,"['Athena', 'Star Mall', 'The Sixth Element Sch...",Tatvam villas is one of the most luxurious res...,"['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '14 L...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Lifestyle4 out of 5...",G66835430
404,3 Bedroom House for sale in Rajendra Park,https://www.99acres.com/3-bhk-bedroom-independ...,NaN,1.3 Crore,"₹ 11,555/sq.ft.",(105 sq.m.) Plot Area,Plot area 1125(104.52 sq.m.),3 Bedrooms,3 Bathrooms,1 Balcony,NaN,"Rajendra Park, Gurgaon, Haryana",2 Floors,North,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Chintapurni Man...",Near to the gurgaon railway station dwarka exp...,NaN,"['Private Garden / Terrace', 'Water Storage', ...","['Environment4 out of 5', 'Lifestyle4 out of 5...",M68603318
802,5 Bedroom House for sale in Palam Vihar,https://www.99acres.com/5-bhk-bedroom-independ...,NaN,6 Crore,"₹ 24,691/sq.ft.",(226 sq.m.) Plot Area,Plot area 270(225.75 sq.m.),5 Bedrooms,6 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Others","Palam Vihar, Gurgaon, Haryana",3 Floors,East,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Very nicely built up independent duplex house ...,"['7 Wardrobe', '12 Fan', '1 Exhaust Fan', '7 G...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5...",B67592164
972,3 Bedroom House for sale in Sector 15 Part 1,https://www.99acres.com/3-bhk-bedroom-independ...,NaN,4.1 Crore,"₹ 22,331/sq.ft.",(171 sq.m.) Plot Area,Plot area 204(170.57 sq.m.)Built Up area: 200 ...,3 Bedrooms,3 Bathrooms,2 Balconies,"Pooja Room,Study Room,Others","Sector 15, Sector 15 Part 1, Gurgaon, Haryana",1 Floors,North-East,10+ Year Old,"['Rajiv Chowk Mosque', 'Hanuman Mandir', 'Hdfc...",House for sale plot size 204 sqyard part one n...,"['5 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Safety4 out of 5', ...",I70274398

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1044 entries, 0 to 1043
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    1044 non-null   object
 1   link             1044 non-null   object
 2   society          453 non-null    object
 3   price            968 non-null    object
 4   price_per_sqft   1005 non-null   object
 5   area             1044 non-null   object
 6   areaWithType     987 non-null    object
 7   bedRoom          987 non-null    object
 8   bathroom         987 non-null    object
 9   balcony          987 non-null    object
 10  additionalRoom   589 non-null    object
 11  address          1031 non-null   object
 12  noOfFloor        967 non-null    object
 13  facing           674 non-null    object
 14  agePossession    987 non-null    object
 15  nearbyLocations  913 non-null    object
 16  description      1036 non-null   object
 17  furnishDetails   743 non-null    object
 18  features         674 non-null    object
 19  rating           907 non-null    object
 20  property_id      1036 non-null   object
dtypes: object(21)
memory usage: 171.4+ KB

In [5]:
# Checking for duplicates
df.duplicated().sum()
df.drop_duplicates(inplace=True)
df.duplicated().sum()

np.int64(0)

In [6]:
# Dropping link and prop_id because they are of no use in this analysis
df.drop(columns=['link','property_id'], inplace = True)

In [7]:
df.sample(6)

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
326,4 Bedroom House for sale in Sector 52 Gurgaon,NaN,NaN,NaN,(201 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
532,5 Bedroom House for sale in Jyoti Park,NaN,1.2 Crore,"₹ 11,194/sq.ft.",(100 sq.m.) Built-up Area,Built Up area: 1072 (99.59 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,NaN,"Jyoti Park, Sector 7, Jyoti Park, Gurgaon, Har...",3 Floors,NaN,undefined,"['State bank ATM', 'Dr. Madan Clinic', 'Taneja...",5bhk residential house for resale in jyoti par...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
737,5 Bedroom House for sale in Nirvana Country,Unitech Espace,10.45 Crore,"₹ 32,253/sq.ft.",(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.),5 Bedrooms,7 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room,Others","Es-201, Nirvana Country, Gurgaon, Haryana",3 Floors,NaN,5 to 10 Year Old,"['Radhakrishna Shani Mandir', 'Standard charte...",Available for sale well maintained villa in es...,"['1 Water Purifier', '1 Fan', '1 Exhaust Fan',...","['Centrally Air Conditioned', 'Water purifier'...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
480,1 Bedroom House for sale in sector-5 sheetla c...,NaN,30 Lac,"₹ 5,555/sq.ft.",(50 sq.m.) Plot Area,Plot area 540(50.17 sq.m.),1 Bedroom,1 Bathroom,2 Balconies,NaN,"sector-5 sheetla colony, Gurgaon, Haryana",1 Floors,NaN,0 to 1 Year Old,NaN,Interested to sell a 2roomset independent hous...,NaN,NaN,NaN
280,5 Bedroom House for sale in Jyoti Park,NaN,1.16 Crore,"₹ 11,693/sq.ft.",(92 sq.m.) Plot Area,Plot area 992(92.16 sq.m.)Carpet area: 992 sq....,5 Bedrooms,4 Bathrooms,2 Balconies,Others,"Jyoti Park, Gurgaon, Haryana",3 Floors,North-East,5 to 10 Year Old,"['State bank ATM', 'Dr. Madan Clinic', 'Taneja...",110 sq yards well built up house for sale\nFac...,"['2 Wardrobe', '1 Modular Kitchen', '5 Curtain...","['Private Garden / Terrace', 'Water Storage', ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
63,4 Bedroom House for sale in Sector 109 Gurgaon,International City by SOBHA Phase 2,NaN,"₹ 13,909/sq.ft.",(384-392 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."

In [8]:
df.price.value_counts()

price
3.5 Crore           19
5.5 Crore           17
6.5 Crore           16
6 Crore             14
75 Lac              13
70 Lac              13
4.5 Crore           13
5 Crore             13
50 Lac              13
8 Crore             13
85 Lac              12
7 Crore             12
8.5 Crore           12
4 Crore             11
1.5 Crore           11
Price on Request    10
60 Lac              10
90 Lac              10
2.5 Crore           10
10 Crore            10
9 Crore             10
45 Lac              10
2.25 Crore          10
1.7 Crore            9
9.5 Crore            9
1.1 Crore            9
12 Crore             9
2 Crore              9
80 Lac               9
11 Crore             8
6.75 Crore           8
1 Crore              8
4.6 Crore            8
1.6 Crore            8
12.5 Crore           7
65 Lac               7
95 Lac               7
3.75 Crore           7
2.1 Crore            7
1.35 Crore           7
55 Lac               7
1.3 Crore            7
1.2 Crore            7
40 Lac               7
2.75 Crore           6
5.7 Crore            6
2.95 Crore           6
4.25 Crore           6
7.5 Crore            6
13.5 Crore           6
3.25 Crore           6
10.5 Crore           6
6.25 Crore           6
1.15 Crore           6
3.6 Crore            6
16 Crore             6
1.45 Crore           6
35 Lac               5
3 Crore              5
1.8 Crore            5
2.8 Crore            5
7.25 Crore           5
5.6 Crore            5
38 Lac               5
4.75 Crore           5
15 Crore             5
1.25 Crore           5
9.25 Crore           4
11.5 Crore           4
4.35 Crore           4
5.75 Crore           4
17 Crore             4
3.2 Crore            4
18 Crore             4
4.7 Crore            4
6.8 Crore            4
1.65 Crore           4
1.4 Crore            4
13 Crore             4
3.3 Crore            4
42 Lac               4
2.4 Crore            4
37 Lac               4
5.8 Crore            4
8.25 Crore           4
5.25 Crore           4
20 Crore             3
1.95 Crore           3
4.45 Crore           3
7.35 Crore           3
8.4 Crore            3
3.4 Crore            3
7.2 Crore            3
1.16 Crore           3
6.95 Crore           3
2.3 Crore            3
2.2 Crore            3
82 Lac               3
34 Lac               3
49 Lac               3
62 Lac               3
32 Lac               3
5.65 Crore           3
19 Crore             3
1.9 Crore            3
2.9 Crore            3
4.3 Crore            3
1.85 Crore           3
92 Lac               3
5.15 Crore           3
3.1 Crore            3
6.4 Crore            3
1.55 Crore           3
3.85 Crore           3
3.05 Crore           2
6.3 Crore            2
66 Lac               2
11.25 Crore          2
3.55 Crore           2
19.5 Crore           2
26 Crore             2
67 Lac               2
3.51 Crore           2
11.75 Crore          2
10.45 Crore          2
11.95 Crore          2
3.15 Crore           2
1.05 Crore           2
15.5 Crore           2
9.9 Crore            2
14 Crore             2
7.1 Crore            2
2.55 Crore           2
89 Lac               2
8.49 Crore           2
4.95 Crore           2
48 Lac               2
30 Lac               2
58 Lac               2
1.75 Crore           2
36 Lac               2
10.85 Crore          2
58.25 Lac            2
3.65 Crore           2
2.15 Crore           2
3.35 Crore           2
10.55 Crore          2
4.12 Crore           1
5.51 Crore           1
3.49 Crore           1
8.48 Crore           1
11.58 Crore          1
4.31 Crore           1
5.46 Crore           1
7.6 Crore            1
10.56 Crore          1
10.75 Crore          1
8.2 Crore            1
4.05 Crore           1
9.35 Crore           1
1.64 Crore           1
9.19 Crore           1
2.99 Crore           1
9.85 Crore           1
1.18 Crore           1
9.01 Crore           1
4.99 Crore           1
9.8 Crore            1
15.1 Crore           1
8.75 Crore           1
25 Crore             1
2.68 Crore           1
2.45 Crore           1
23 Crore             1
1.72 Crore           1
63 Lac               1
53 Lac               1
51 Lac               1
8.95 Crore           1
13.2 Crore           1
7.5 Lac              1
2.58 Crore           1
4.02 Crore           1
22 Lac               1
3.12 Crore           1
6.6 Crore            1
61 Lac               1
7.05 Crore           1
3.69 Crore           1
11.3 Crore           1
1.87 Crore           1
8.7 Crore            1
6.2 Crore            1
5.35 Crore           1
5.85 Crore           1
5.9 Crore            1
2.7 Crore            1
1.04 Crore           1
7.85 Crore           1
3.93 Crore           1
2.35 Crore           1
18.25 Crore          1
8.6 Crore            1
9.55 Crore           1
15.5 Lac             1
71 Lac               1
69 Lac               1
74 Lac               1
3.09 Crore           1
47.5 Lac             1
83 Lac               1
98 Lac               1
24 Lac               1
44 Lac               1
18 Lac               1
65.8 Lac             1
96 Lac               1
46 Lac               1
1.34 Crore           1
18.02 Crore          1
2.43 Crore           1
13 Lac               1
59 Lac               1
47 Lac               1
52.5 Lac             1
1.44 Crore           1
3.08 Crore           1
29 Lac               1
3.71 Crore           1
78 Lac               1
4.65 Crore           1
6.1 Crore            1
1.07 Crore           1
68 Lac               1
5.2 Crore            1
42.75 Lac            1
52 Lac               1
1.52 Crore           1
8.81 Crore           1
6.81 Crore           1
3.99 Crore           1
59.95 Lac            1
7.46 Crore           1
24 Crore             1
18.9 Crore           1
17.3 Crore           1
27 Lac               1
9.54 Crore           1
14.75 Crore          1
8.1 Crore            1
2.6 Crore            1
3.87 Crore           1
1.39 Crore           1
12.39 Crore          1
8.8 Crore            1
7.99 Crore           1
5.4 Crore            1
4.49 Crore           1
4.15 Crore           1
55.11 Lac            1
7.3 Crore            1
7.69 Crore           1
18.5 Crore           1
27.5 Crore           1
8.31 Crore           1
6.21 Crore           1
1.83 Crore           1
7.49 Crore           1
22 Crore             1
8.9 Crore            1
2.01 Crore           1
3.9 Crore            1
5.1 Crore            1
5.88 Crore           1
12.25 Crore          1
46.75 Lac            1
9.4 Crore            1
52.75 Lac            1
8.45 Crore           1
6.15 Crore           1
2.47 Crore           1
3.7 Crore            1
18.4 Crore           1
4.4 Crore            1
99 Lac               1
10.3 Crore           1
2.65 Crore           1
1.27 Crore           1
11.29 Crore          1
5.3 Crore            1
10.8 Crore           1
31.5 Crore           1
4.1 Crore            1
7.65 Crore           1
6.46 Crore           1
6.44 Crore           1
7.8 Crore            1
3.8 Crore            1
7.45 Crore           1
7.42 Crore           1
6.09 Crore           1
2.98 Crore           1
Name: count, dtype: int64

In [9]:
df.price.isnull().sum()

np.int64(76)

In [10]:
# prices are in lac, crore and price on request. Convert all into crores
#dropping the ones with Price on Request category

df = df[df['price']!= 'Price on Request']
def convert_to_crore(value):
    if type(value) == float:
        return value
    else:
        amt = str(value).split(" ")[0]
        unit = str(value).split(" ")[1]
        if unit != 'Crore':
            return round(float(amt)/100,2)
        else:
            return round(float(amt),2)

df['price'] = df['price'].apply(convert_to_crore)

In [11]:
df['price_per_sqft'].isnull().sum()

np.int64(29)

In [12]:
df.dropna(subset=['price_per_sqft'],inplace = True)

In [13]:
df['price_per_sqft'] = df['price_per_sqft'].apply(lambda x: re.sub(r'/.+','',str(x).replace(',','').replace('₹',''))).astype('float')
df['price_per_sqft']

0        20115.0
1       105751.0
2        38251.0
3        43066.0
4        53763.0
5        39062.0
6        37037.0
7        48889.0
8        38150.0
9        10077.0
10       32963.0
11       27778.0
12       34083.0
13       33200.0
14       30556.0
15       14914.0
16       29861.0
17       23333.0
18       41762.0
19       15451.0
20       12938.0
21       38095.0
22       25926.0
23       26235.0
24       38760.0
25       25926.0
26        9374.0
27       13410.0
28       21124.0
29       32593.0
30       24170.0
31       37037.0
32       28490.0
33      122222.0
34       13542.0
35       19097.0
36       48148.0
37       22222.0
38       22222.0
39       33333.0
40       32222.0
41        7290.0
42       27741.0
43       50000.0
44       43534.0
45       45889.0
46       34722.0
48       20690.0
49       29716.0
50       16378.0
51       17284.0
52       37777.0
53       12519.0
54       25562.0
55       27971.0
56       21000.0
57       24500.0
58        7058.0
59        7058.0
60       11250.0
61       23333.0
62       13622.0
63       13909.0
64       20000.0
65       35400.0
66       16058.0
67       16058.0
68       13623.0
69       13910.0
70       13910.0
71       12027.0
72       15700.0
73       19708.0
74       16039.0
75       13331.0
76       11100.0
77       11100.0
78       11100.0
79       40135.0
80       16244.0
81       19708.0
82       16039.0
83       11100.0
84       11100.0
85       16999.0
86       10714.0
87       12027.0
90       21605.0
91       10463.0
92       18750.0
93       19000.0
94       27793.0
95       22006.0
96       19000.0
97       13333.0
98       22222.0
99       28760.0
100      16975.0
101      41615.0
102      16058.0
103      15700.0
106      14444.0
107      10101.0
108      38703.0
109      22222.0
110      12828.0
111      12842.0
112      23148.0
113       8557.0
114      16428.0
116      10556.0
117      13519.0
118      42032.0
119      24069.0
120      21605.0
121      13889.0
122      14650.0
123      13889.0
124      13778.0
125      15625.0
126      23333.0
127      21250.0
128      38667.0
129      26667.0
130      12593.0
131      26389.0
132      12963.0
133      25514.0
134      24845.0
135      17650.0
136      24280.0
137      26423.0
138       6666.0
139       8916.0
140      36667.0
141       9000.0
142      20000.0
143       9028.0
144       4074.0
145        630.0
146      86567.0
147      92857.0
148     100000.0
149      88157.0
150      29974.0
151      24691.0
152       2778.0
153      46906.0
154      25000.0
155      23699.0
156      25960.0
157      28424.0
158      33333.0
159       4490.0
160      14729.0
161      25111.0
162      25000.0
163       7309.0
164      10556.0
165      74074.0
166      12000.0
167      10233.0
168      26852.0
169       8878.0
170      14286.0
171       8928.0
172       8007.0
173      11111.0
174       5698.0
175      28283.0
176      24214.0
177      26613.0
178     138888.0
179      10000.0
180       7666.0
181       7407.0
182       8333.0
183       4666.0
184      13333.0
185      60000.0
186      11111.0
187       7778.0
188      40775.0
189      99173.0
190      12222.0
191       6172.0
192      22222.0
193       9111.0
194      80357.0
195       4117.0
196       7308.0
197       8701.0
198       8000.0
199      25926.0
200       6666.0
201       2296.0
202       8888.0
203      33333.0
204      12444.0
205       9793.0
206       6250.0
207       8486.0
208      11717.0
209       7589.0
210      13333.0
211      12592.0
212      15384.0
213       7843.0
214      22222.0
215      23333.0
216      29336.0
217      10288.0
218      11284.0
219      11029.0
220      10277.0
221       6944.0
222       8518.0
223      10555.0
224      11250.0
225        557.0
226       8888.0
227      11852.0
228       8947.0
229      39265.0
230       6083.0
231     230547.0
232       8411.0
233      32291.0
234      41666.0
235       8889.0
236       7280.0
237      90000.0
238      10089.0
239       8697.0
240       8500.0
241       9333.0
242       8235.0
243      13333.0
244      21667.0
245      20425.0
246       5472.0
247       6944.0
248      57692.0
249      60000.0
251       3857.0
252      21759.0
253       8333.0
254       7407.0
255      75000.0
256      10482.0
257      25386.0
258       8735.0
259       9444.0
262      20000.0
263      18667.0
264      18889.0
265       2525.0
266      24306.0
267      17695.0
268      21519.0
269      17817.0
270          2.0
271       6173.0
272      55000.0
274      13888.0
275      20323.0
276      20359.0
279       5833.0
280      11693.0
281      26667.0
282      53125.0
283      17900.0
285      39886.0
286     126865.0
287      40909.0
288      27155.0
289      14492.0
292      13622.0
293      14045.0
294      10783.0
295      10804.0
296      10783.0
297      14167.0
298      11111.0
300      13157.0
301       5888.0
302      11111.0
303       7875.0
304       9654.0
305       4808.0
306       8222.0
307      11111.0
308       3857.0
309      50000.0
310      11273.0
311       8000.0
312       7627.0
313       5666.0
314       5000.0
315       5000.0
316       6567.0
317      22068.0
318      13333.0
319       6666.0
320      66666.0
321       7500.0
322       8386.0
323      12444.0
324      25000.0
325       6944.0
327      11111.0
328      28674.0
329       9725.0
330      21111.0
331       7500.0
332      10784.0
333      12162.0
334       8910.0
335      10518.0
336      19869.0
337       8796.0
338       9722.0
339       7522.0
340       5658.0
341       5000.0
342      24545.0
343       7701.0
344       8235.0
345      14072.0
346      26000.0
347      24305.0
348      19286.0
349      22634.0
350      26570.0
351      11111.0
352       6410.0
353     133079.0
354      15257.0
356       5778.0
357       6111.0
358      15625.0
359      78125.0
360      17955.0
361       7916.0
362     211111.0
363      80000.0
364      35000.0
365      10000.0
366     120000.0
367      22297.0
368     125000.0
369       8889.0
370      73333.0
372      11111.0
373      26235.0
374       6790.0
375      20833.0
376     315789.0
377      10224.0
378       3500.0
379       3285.0
380      74000.0
381      27139.0
382      10000.0
383       5555.0
385      23662.0
386      17574.0
387      13333.0
388      10753.0
389       9091.0
390      23557.0
391      59259.0
392     105263.0
393      21195.0
394        151.0
395      25103.0
396      13889.0
397      14954.0
398      23333.0
399       8784.0
400       6500.0
401      35494.0
402      11464.0
403      11718.0
404      11555.0
405      50000.0
406       3874.0
407       7576.0
408      11556.0
409      10753.0
410      20635.0
411      10378.0
412      11888.0
413      17284.0
414      32258.0
415      11111.0
416      12222.0
417      16389.0
418      31506.0
419       9722.0
420      12820.0
421     229885.0
422      10000.0
423       8889.0
424      12400.0
425       9259.0
426        232.0
427      15257.0
428     218750.0
429      54794.0
430      14245.0
431       6367.0
432      37313.0
433      90909.0
434       9444.0
435       5000.0
437      10122.0
438      10000.0
439       8642.0
440       6481.0
441       6707.0
442     245398.0
443       9259.0
445      11904.0
446       9135.0
448       7111.0
449       8012.0
450     183333.0
451      12500.0
452      10142.0
453       8444.0
454       8125.0
455      14583.0
456      17037.0
457      11538.0
458       8730.0
459      12222.0
460      14444.0
461      11574.0
463      26667.0
464      11111.0
465       8230.0
466      13095.0
467      30556.0
468      11852.0
469      10000.0
470      29311.0
471      11250.0
472      30384.0
473       8444.0
474      19818.0
475       1992.0
476       7619.0
477      98214.0
478      13499.0
479       7820.0
480       5555.0
481       4000.0
482      14720.0
483       5664.0
484      19753.0
485      76000.0
486      37037.0
487      63492.0
488       9000.0
489       4444.0
490       2500.0
491       6667.0
492       3704.0
493      12777.0
494       6648.0
495      11407.0
496      20233.0
497      17778.0
498      20062.0
499      11494.0
500      25543.0
501      12343.0
502      16892.0
503       8000.0
504      17500.0
505       3904.0
506      14323.0
507       4222.0
508     181818.0
509      75000.0
510      26620.0
511       5555.0
512      10000.0
513       9722.0
514       9500.0
515      17937.0
516       3254.0
517       5333.0
518      30556.0
519       4583.0
520      12500.0
521      21875.0
523      16667.0
524       7075.0
525       8078.0
526       4251.0
527      17584.0
528       5397.0
529       9074.0
530       5583.0
531       3519.0
532      11194.0
533     100000.0
534       6981.0
535       6702.0
536       9444.0
537      10556.0
538      18333.0
539       4877.0
540       7479.0
541       7400.0
542      16003.0
543       8000.0
544       9444.0
545       9103.0
546       7727.0
547      45710.0
549       8702.0
550       5950.0
551       3500.0
552       9722.0
553       8889.0
554      26973.0
555      32407.0
556      13750.0
557       6000.0
558      14890.0
559       9210.0
560       6800.0
561      10518.0
562       7333.0
563       8101.0
564       6944.0
565      14184.0
566       4260.0
567      10582.0
568       9390.0
569      84000.0
570       6938.0
571      15555.0
572      33333.0
573       7539.0
574      10000.0
575      10067.0
576       1649.0
577      10000.0
578      10000.0
579      13000.0
580      28898.0
581      28200.0
582       7168.0
583      20444.0
585      35185.0
586       6289.0
587      17857.0
588       7000.0
589      14166.0
590      30968.0
591       7777.0
592      18658.0
593      10484.0
594     160000.0
595       8127.0
596       5000.0
597       8000.0
598       7555.0
599      49500.0
600       8889.0
601      13030.0
602     308333.0
603       8333.0
604      10610.0
605      18889.0
606       7302.0
607       8155.0
608      10591.0
609      24074.0
610      14815.0
611       5160.0
612     144444.0
613       9615.0
614       9444.0
615      10101.0
616      22222.0
617      32407.0
618       6813.0
619      15046.0
620      11583.0
622       6034.0
623      10085.0
624      17778.0
625      40611.0
626      29630.0
627      29629.0
628      10740.0
629       4444.0
630      17980.0
631      55000.0
632      19737.0
633       5093.0
634      25463.0
635      12000.0
636       7007.0
637       8920.0
638      35294.0
639      12963.0
640       8254.0
641       5128.0
642       5777.0
643      15926.0
644      11111.0
645      14285.0
646      34307.0
647      51864.0
648      44265.0
649      29444.0
650      39074.0
651      38734.0
652      23442.0
653      41833.0
654      27778.0
655     600000.0
656      23889.0
657      25000.0
658      10260.0
659      31915.0
660      11102.0
661       8866.0
662      36911.0
663      36111.0
664      15444.0
665      11240.0
666      15437.0
667      14351.0
668      27191.0
669     241666.0
670      32963.0
671      33592.0
672      24455.0
673      26667.0
674      26389.0
675     194444.0
676      18444.0
677      11600.0
678      38095.0
679      13492.0
680      33951.0
681      11157.0
682       8444.0
683      21495.0
684      42054.0
685       1560.0
686      20741.0
687      13178.0
688      12000.0
689      26428.0
690      82540.0
691      18888.0
692      31481.0
693      13501.0
694      20988.0
695     400000.0
696      21296.0
697      34722.0
698      18626.0
699      24366.0
700      26298.0
701       7500.0
702      24171.0
703      23000.0
704      29697.0
705      33333.0
706      36111.0
707       6778.0
708      22812.0
709     261194.0
710     178571.0
711      27461.0
712      31686.0
713      22222.0
714      23061.0
715      32222.0
716      17662.0
717      39841.0
718      37627.0
719      23148.0
720      29880.0
721      20068.0
722      16569.0
723      21242.0
724      11574.0
725      32562.0
726      13000.0
727      22429.0
728      39530.0
729      22222.0
730      38889.0
732      57206.0
733      27222.0
734      63554.0
735      10601.0
736      20940.0
737      32253.0
738      37037.0
740      23704.0
741      23693.0
742      15989.0
743      19268.0
744      19360.0
745      45833.0
746      29880.0
747      23437.0
748       2716.0
749      39841.0
750      32222.0
751      40850.0
752      12342.0
753      15555.0
754      26111.0
755      31790.0
756      24691.0
757     235376.0
758      29293.0
759      16004.0
760      27333.0
761      17624.0
762      38580.0
763      27778.0
764      35556.0
765      38580.0
766      35000.0
767      30864.0
769     161849.0
770      27778.0
771      16056.0
772      17707.0
785       7718.0
786      25535.0
787       1859.0
788      17037.0
789      10579.0
790      42194.0
791      15625.0
792      15278.0
793     201388.0
794      17187.0
796      44444.0
797      18928.0
798      10926.0
799      19608.0
800       8089.0
801       6849.0
802      24691.0
804      19607.0
805      40000.0
806      34846.0
807      31444.0
808      26235.0
809      22222.0
810      23457.0
811      27083.0
812      43210.0
813      31926.0
814      38611.0
815      27911.0
816      29022.0
817      12837.0
818      12198.0
819      35741.0
821      16666.0
822      35556.0
823       9634.0
825      31481.0
826       7827.0
827      38760.0
828      23556.0
829      10035.0
830      28841.0
831      26615.0
832      24155.0
833      14815.0
834      22222.0
835      62222.0
836       6597.0
837       7870.0
838      26852.0
839      28233.0
840      15111.0
841      34722.0
842      19820.0
843       1087.0
845      31481.0
846      26235.0
847      19645.0
848      36883.0
849      37037.0
850      27871.0
851      35109.0
852      17692.0
853      38022.0
854      33333.0
855      25309.0
856      16990.0
857      14222.0
858      22222.0
859      16388.0
860      22075.0
861      11666.0
862      47167.0
863       7937.0
864      20197.0
865      20635.0
866      34037.0
867      10123.0
868      28858.0
869      28549.0
870      15555.0
871      13513.0
872      20769.0
873      34568.0
874      21097.0
875      33951.0
876      24306.0
877      25556.0
878      36111.0
879       7756.0
880      21825.0
881      12342.0
882      16577.0
883      17706.0
884      29074.0
885      29880.0
886      42222.0
887      38194.0
888      21605.0
889      38194.0
890      37778.0
891      31111.0
892      17213.0
893      18620.0
894      17014.0
895       7750.0
896       7172.0
897      29638.0
898      33333.0
899       8137.0
900       7582.0
901      48148.0
902      18605.0
903      16066.0
904      55556.0
905      38986.0
906      24510.0
907      11428.0
908      22184.0
909      30247.0
910      20370.0
911      31666.0
912      18889.0
913     283333.0
914      31481.0
915      42222.0
916      59259.0
917      45833.0
918      18008.0
919      26235.0
921      33333.0
922      12285.0
923      19293.0
924      20599.0
925     173992.0
926      21367.0
927      20299.0
928      41818.0
929       9634.0
930      19231.0
931      20833.0
932      33333.0
933       6875.0
934      14667.0
935      14787.0
936      16319.0
937      18250.0
938      27390.0
939      30728.0
940      35000.0
941      30556.0
942      41315.0
943       3786.0
944      60000.0
945      24691.0
946       9349.0
947      23504.0
948      21605.0
949     234375.0
950      26235.0
951      21786.0
952      35000.0
953       8235.0
954      15432.0
955      37627.0
956      21251.0
957      30556.0
958      27160.0
959      35530.0
960      22046.0
961      22222.0
962      33333.0
963      27132.0
964      22855.0
965      40741.0
966      34722.0
967      29333.0
968      32328.0
969     290948.0
970      25562.0
971      12393.0
972      22331.0
973      20317.0
974      18088.0
975      21759.0
976      16600.0
977      21219.0
978      19125.0
979      18885.0
980      15000.0
981      37037.0
982      18814.0
983      32328.0
984      23457.0
985      16975.0
986      18889.0
987      14000.0
988      32407.0
989     266666.0
990      26502.0
991      23148.0
992      32407.0
993      33951.0
994      18808.0
995      31481.0
996      10838.0
997      19847.0
998      23148.0
999      12037.0
1000     17820.0
1001     24390.0
1002     35185.0
1004     26063.0
1005     79365.0
1006     23932.0
1007     24573.0
1008     24005.0
1009     32870.0
1010     33404.0
1011     23240.0
1012     29630.0
1013     16071.0
1014     51440.0
1015     26667.0
1016     28782.0
1017     34491.0
1018     34351.0
1019     47803.0
1020      6230.0
1021     33665.0
1022     44444.0
1025     20566.0
1026     22222.0
1027     26667.0
1028     20349.0
1029     23148.0
1030     21124.0
1031     24202.0
1032     24155.0
1033     23870.0
1034     24500.0
1035     24845.0
1036     20026.0
1037     28787.0
1038     12551.0
1039     30556.0
1040     31481.0
1041     33333.0
1042     33129.0
1043     14815.0
Name: price_per_sqft, dtype: float64

In [14]:
df['society'].value_counts().shape

(181,)

In [15]:
# There are some ratings at the end of society name, thus cleaning is required
df['society'] = df['society'].fillna('independent')
df['society'] = df['society'].apply(lambda x: re.sub(r'\d+(\.\d)?\s?★?','',str(x)).strip().lower())
# checking if cleaning done properly!
# df[df['society'].str.contains('★')]

In [16]:
df.sample(6)

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
597,5 Bedroom House for sale in Jacobpura,independent,1.70,8000.0,(186 sq.m.) Built-up Area,Built Up area: 2000 (185.81 sq.m.),5 Bedrooms,5 Bathrooms,3 Balconies,"Pooja Room,Others","Jacobpura, Gurgaon, Haryana",3 Floors,NaN,5 to 10 Year Old,"['Hanuman Mandir', 'Rajiv Memorial Eye Infirma...",Interested to sell independent house/villa.It ...,"['4 Wardrobe', 'No AC', 'No Bed', 'No Chimney'...",['Private Garden / Terrace'],"['Environment3 out of 5', 'Lifestyle4 out of 5..."
403,5 Bedroom House for sale in Laxman Vihar,not applicable,0.75,11718.0,(59 sq.m.) Plot Area,Plot area 640(59.46 sq.m.),5 Bedrooms,4 Bathrooms,3 Balconies,NaN,"Laxman Vihar, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Prat...",I am looking for buyer to purchase house/villa...,[],NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
888,4 Bedroom House for sale in Sushant Lok Phase 3,independent,3.50,21605.0,(151 sq.m.) Plot Area,Plot area 180(150.5 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,Store Room,"78787, Sushant Lok Phase 3, Gurgaon, Haryana",3 Floors,South,10+ Year Old,"['Radhakrishna Shani Mandir', 'Sanatan Dharm M...",Ansal florence villa in 180yds is available fo...,"['6 Wardrobe', '8 Fan', '1 Exhaust Fan', '4 Ge...","['High Ceiling Height', 'Maintenance Staff', '...","['Environment4 out of 5', 'Safety4 out of 5', ..."
133,5 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase,6.20,25514.0,(226 sq.m.) Plot Area,Plot area 270(225.75 sq.m.),5 Bedrooms,5 Bathrooms,2 Balconies,Servant Room,"335, Sector 109 Gurgaon, Gurgaon, Haryana",2 Floors,South-West,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",This comes with one of the largest fully funct...,"['5 Geyser', '8 AC', 'No Bed', 'No Chimney', '...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
910,6 Bedroom House for sale in Palam Vihar,independent,4.95,20370.0,(226 sq.m.) Plot Area,Plot area 270(225.75 sq.m.),6 Bedrooms,5 Bathrooms,3+ Balconies,Servant Room,"Palam Vihar, Gurgaon, Haryana",3 Floors,West,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Two years old constructed independent house 9 ...,NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety4 out of 5', ..."
708,4 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,7.35,22812.0,(299 sq.m.) Plot Area,Plot area 358(299.33 sq.m.),4 Bedrooms,5 Bathrooms,2 Balconies,"Servant Room,Store Room,Study Room,Pooja Room","001, Sector 48 Gurgaon, Gurgaon, Haryana",2 Floors,South,5 to 10 Year Old,"['Athena', 'Star Mall', 'The Sixth Element Sch...",Tatvam villas is one of the most luxurious res...,"['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '14 L...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [17]:
df['area'] = df['area'].str.extract(r'(\d+)').astype('float')
df['area']

0          242.0
1           50.0
2           51.0
3          108.0
4           52.0
5          107.0
6          301.0
7          418.0
8          264.0
9          180.0
10         125.0
11         301.0
12         136.0
13         420.0
14         251.0
15         125.0
16         334.0
17          84.0
18         201.0
19         268.0
20         244.0
21         293.0
22         301.0
23         301.0
24         180.0
25         251.0
26         471.0
27         242.0
28         220.0
29         301.0
30         210.0
31         251.0
32         293.0
33          84.0
34         134.0
35         161.0
36         251.0
37         300.0
38         251.0
39         251.0
40         167.0
41          70.0
42         251.0
43         251.0
44         255.0
45         251.0
46         167.0
48         242.0
49         180.0
50         145.0
51         301.0
52         418.0
53         593.0
54         136.0
55         241.0
56         372.0
57         135.0
58         316.0
59         316.0
60         743.0
61          84.0
62         467.0
63         384.0
64         232.0
65         180.0
66         606.0
67         521.0
68         467.0
69         294.0
70         293.0
71         590.0
72         521.0
73         606.0
74         521.0
75         543.0
76         468.0
77         292.0
78         293.0
79         220.0
80         286.0
81         606.0
82         521.0
83         325.0
84         293.0
85         139.0
86         650.0
87         590.0
90         226.0
91         502.0
92         372.0
93         279.0
94         571.0
95         372.0
96         279.0
97         543.0
98         293.0
99         207.0
100        301.0
101        223.0
102        606.0
103        521.0
106        209.0
107        460.0
108        251.0
109        815.0
110        650.0
111        650.0
112        301.0
113         73.0
114         25.0
116        502.0
117        220.0
118        254.0
119        297.0
120        301.0
121        100.0
122        244.0
123        134.0
124        209.0
125        134.0
126        223.0
127        372.0
128        209.0
129        418.0
130        502.0
131        334.0
132        502.0
133        226.0
134        135.0
135        161.0
136        226.0
137        206.0
138        557.0
139        557.0
140        167.0
141        650.0
142        743.0
143         67.0
144        125.0
145       1254.0
146          6.0
147          7.0
148          6.0
149          7.0
150        180.0
151        226.0
152       2592.0
153        140.0
154        167.0
155        145.0
156         89.0
157        180.0
158        418.0
159        201.0
160        360.0
161        418.0
162        418.0
163        511.0
164        502.0
165         13.0
166         51.0
167         64.0
168         50.0
169         99.0
170        293.0
171         94.0
172         52.0
173         84.0
174         98.0
175        230.0
176        151.0
177        140.0
178          5.0
179         84.0
180        279.0
181         63.0
182         56.0
183         84.0
184         42.0
185          7.0
186         42.0
187         46.0
188         91.0
189         22.0
190        167.0
191        166.0
192        334.0
193         84.0
194         10.0
195        158.0
196        121.0
197        139.0
198         42.0
199        125.0
200        111.0
201         63.0
202         84.0
203        167.0
204        209.0
205        261.0
206        260.0
207        339.0
208         92.0
209        104.0
210         63.0
211         25.0
212        302.0
213         43.0
214        209.0
215        418.0
216        253.0
217        135.0
218        107.0
219        316.0
220         33.0
221        301.0
222        125.0
223         84.0
224         33.0
225       2415.0
226         84.0
227        125.0
228         88.0
229        166.0
230         76.0
231         32.0
232         50.0
233         18.0
234         22.0
235        431.0
236        121.0
237          5.0
238         41.0
239        200.0
240         93.0
241         42.0
242         52.0
243         84.0
244        279.0
245        171.0
246        372.0
247        301.0
248         12.0
249          5.0
251        325.0
252        201.0
253         67.0
254         28.0
255         20.0
256         44.0
257         84.0
258        133.0
259        167.0
262        278.0
263        139.0
264        153.0
265         28.0
266        134.0
267        121.0
268        367.0
269        209.0
270     809371.0
271         90.0
272         19.0
274        167.0
275        160.0
276        135.0
279        111.0
280         92.0
281        557.0
282        149.0
283        465.0
285        326.0
286          6.0
287         31.0
288        452.0
289        385.0
292        540.0
293        363.0
294        468.0
295        292.0
296        293.0
297         33.0
298         92.0
300        177.0
301         84.0
302        167.0
303         74.0
304         34.0
305         87.0
306         42.0
307        144.0
308        325.0
309          9.0
310         51.0
311        929.0
312        219.0
313        279.0
314        102.0
315        279.0
316        219.0
317         13.0
318         33.0
319         49.0
320          7.0
321        372.0
322        233.0
323        418.0
324         93.0
325        167.0
327         54.0
328         52.0
329         75.0
330         42.0
331        478.0
332         57.0
333         34.0
334         89.0
335        132.0
336         71.0
337        100.0
338        100.0
339        105.0
340         95.0
341         84.0
342         51.0
343         84.0
344        158.0
345        340.0
346        232.0
347        134.0
348        650.0
349        226.0
350        115.0
351        146.0
352        109.0
353         24.0
354         56.0
356         84.0
357        167.0
358         45.0
359         15.0
360        220.0
361         45.0
362         25.0
363          9.0
364         56.0
365        102.0
366          5.0
367         50.0
368         33.0
369         84.0
370         14.0
372        251.0
373        301.0
374        151.0
375         33.0
376         18.0
377         75.0
378         93.0
379        325.0
380         23.0
381        291.0
382         84.0
383         84.0
385        226.0
386        246.0
387        435.0
388         52.0
389        460.0
390         47.0
391         50.0
392          5.0
393         85.0
394       7692.0
395        226.0
396         33.0
397        124.0
398         84.0
399        132.0
400         93.0
401        301.0
402         73.0
403         59.0
404        105.0
405          7.0
406        163.0
407        184.0
408        105.0
409         52.0
410        293.0
411         49.0
412         84.0
413        113.0
414        132.0
415         84.0
416         84.0
417        167.0
418        136.0
419         33.0
420        109.0
421         40.0
422        483.0
423         42.0
424         46.0
425         50.0
426      20064.0
427         56.0
428         15.0
429         14.0
430         98.0
431        328.0
432        336.0
433          5.0
434        167.0
435         84.0
437        110.0
438        167.0
439        151.0
440         56.0
441         76.0
442         15.0
443         40.0
445        234.0
446         43.0
448         42.0
449         58.0
450         28.0
451         56.0
452         65.0
453         42.0
454        372.0
455         33.0
456        125.0
457        121.0
458        117.0
459        125.0
460         84.0
461        100.0
463         50.0
464         42.0
465        113.0
466        390.0
467        167.0
468         63.0
469         84.0
470        136.0
471         74.0
472         99.0
473         42.0
474        174.0
475       6062.0
476         49.0
477          5.0
478         89.0
479         89.0
480         50.0
481         42.0
482         98.0
483         52.0
484        188.0
485          5.0
486        301.0
487        117.0
488         46.0
489        251.0
490        149.0
491        139.0
492        125.0
493         84.0
494         98.0
495        251.0
496        135.0
497        418.0
498        301.0
499        242.0
500        291.0
501        207.0
502        124.0
503        167.0
504        204.0
505        195.0
506        681.0
507         84.0
508         51.0
509          9.0
510        161.0
511         84.0
512         33.0
513         33.0
514         93.0
515         83.0
516         83.0
517         42.0
518        167.0
519        111.0
520        372.0
521         84.0
523         84.0
524        138.0
525        207.0
526         96.0
527         44.0
528        121.0
529        100.0
530        557.0
531        125.0
532        100.0
533         84.0
534        339.0
535        437.0
536        167.0
537        418.0
538         84.0
539        162.0
540        248.0
541         93.0
542        107.0
543         46.0
544         84.0
545         70.0
546        102.0
547        264.0
549        139.0
550        281.0
551        186.0
552         67.0
553        251.0
554        115.0
555        201.0
556        111.0
557         93.0
558        152.0
559        353.0
560         46.0
561         66.0
562         70.0
563         80.0
564        836.0
565         79.0
566        107.0
567        176.0
568         37.0
569          5.0
570        100.0
571        209.0
572        125.0
573        143.0
574         84.0
575         69.0
576         73.0
577         88.0
578        125.0
579         46.0
580        354.0
581        594.0
582         76.0
583        209.0
585         50.0
586        222.0
587        130.0
588         93.0
589         56.0
590         60.0
591         84.0
592         44.0
593         71.0
594          9.0
595        102.0
596        249.0
597        186.0
598         42.0
599        186.0
600         42.0
601        153.0
602          6.0
603         50.0
604         51.0
605         84.0
606         59.0
607         91.0
608         51.0
609        100.0
610        125.0
611        151.0
612          4.0
613        217.0
614         84.0
615        184.0
616        420.0
617        100.0
618         75.0
619        401.0
620         50.0
622        108.0
623         54.0
624        209.0
625        286.0
626         50.0
627         50.0
628        251.0
629         84.0
630         84.0
631         93.0
632        318.0
633       1003.0
634        100.0
635         21.0
636         93.0
637         99.0
638        213.0
639        502.0
640         44.0
641        109.0
642        105.0
643        420.0
644        125.0
645        650.0
646        420.0
647        264.0
648        420.0
649        301.0
650        251.0
651        420.0
652        145.0
653        420.0
654        301.0
655         37.0
656         84.0
657         84.0
658        590.0
659        196.0
660         50.0
661        418.0
662        171.0
663        167.0
664        418.0
665        579.0
666        232.0
667        201.0
668        301.0
669          6.0
670        251.0
671        180.0
672        171.0
673        836.0
674        334.0
675         33.0
676        209.0
677        232.0
678        293.0
679        585.0
680        301.0
681        112.0
682        209.0
683        140.0
684        420.0
685        180.0
686        251.0
687        180.0
688        186.0
689        650.0
690        336.0
691         84.0
692         50.0
693        299.0
694        301.0
695         23.0
696        201.0
697        334.0
698        145.0
699       1049.0
700        283.0
701         51.0
702        319.0
703        251.0
704        230.0
705        125.0
706        167.0
707        251.0
708        299.0
709         37.0
710         14.0
711        220.0
712        180.0
713        334.0
714        222.0
715        125.0
716        145.0
717        420.0
718        420.0
719        151.0
720        420.0
721        220.0
722        286.0
723        171.0
724        502.0
725        301.0
726        144.0
727        135.0
728        222.0
729        251.0
730        136.0
732        422.0
733        201.0
734          8.0
735         41.0
736        543.0
737        301.0
738        301.0
740        305.0
741        171.0
742        171.0
743        145.0
744         55.0
745        167.0
746        420.0
747        595.0
748        180.0
749        420.0
750        167.0
751        393.0
752        264.0
753        190.0
754        334.0
755        301.0
756        226.0
757         33.0
758        230.0
759        226.0
760        226.0
761        242.0
762        301.0
763        334.0
764        418.0
765        301.0
766        418.0
767        301.0
769         16.0
770        226.0
771        145.0
772        420.0
785        297.0
786        135.0
787        420.0
788        251.0
789        321.0
790        264.0
791        268.0
792        268.0
793         33.0
794         54.0
796        418.0
797        201.0
798        251.0
799        171.0
800        146.0
801        102.0
802        226.0
804        308.0
805        418.0
806        301.0
807        251.0
808        301.0
809        251.0
810        376.0
811        669.0
812        253.0
813        125.0
814        161.0
815        350.0
816        336.0
817        420.0
818        350.0
819        301.0
821        223.0
822        418.0
823        579.0
825        201.0
826        297.0
827        180.0
828        334.0
829        579.0
830        350.0
831        180.0
832        135.0
833        226.0
834        251.0
835        209.0
836        225.0
837        201.0
838        251.0
839        510.0
840        209.0
841        301.0
842        155.0
843       4699.0
845        251.0
846        301.0
847        220.0
848        301.0
849        301.0
850        250.0
851        450.0
852        350.0
853        220.0
854        418.0
855        301.0
856        302.0
857        209.0
858        334.0
859        167.0
860        128.0
861        181.0
862        167.0
863        509.0
864        161.0
865        135.0
866        251.0
867        151.0
868        301.0
869        301.0
870        142.0
871        142.0
872        159.0
873        226.0
874        264.0
875        301.0
876        334.0
877        836.0
878        167.0
879         50.0
880        234.0
881        264.0
882        537.0
883        286.0
884        251.0
885        420.0
886        418.0
887        134.0
888        151.0
889        293.0
890        418.0
891        836.0
892        145.0
893        135.0
894        134.0
895        110.0
896        135.0
897        350.0
898        418.0
899        135.0
900        110.0
901        251.0
902        754.0
903        521.0
904        301.0
905        286.0
906         85.0
907        650.0
908        241.0
909        301.0
910        226.0
911        836.0
912        226.0
913         22.0
914        136.0
915        253.0
916        293.0
917        176.0
918        242.0
919        171.0
921        136.0
922        650.0
923        460.0
924        223.0
925         51.0
926        217.0
927        217.0
928         26.0
929        579.0
930        435.0
931        161.0
932        251.0
933        297.0
934        209.0
935        220.0
936        134.0
937         51.0
938        180.0
939        189.0
940        167.0
941        167.0
942        264.0
943        466.0
944        242.0
945        241.0
946        161.0
947        217.0
948        151.0
949         15.0
950        151.0
951        171.0
952        836.0
953        158.0
954        301.0
955        420.0
956        521.0
957         50.0
958        376.0
959        288.0
960        158.0
961        142.0
962        125.0
963        180.0
964        264.0
965        301.0
966        201.0
967        314.0
968        194.0
969         22.0
970        136.0
971        109.0
972        171.0
973        293.0
974        180.0
975        201.0
976        420.0
977        241.0
978        372.0
979        253.0
980        418.0
981        251.0
982        420.0
983        194.0
984        420.0
985        301.0
986        318.0
987        372.0
988        301.0
989         28.0
990        226.0
991        301.0
992        201.0
993        301.0
994        321.0
995        201.0
996        579.0
997        220.0
998        301.0
999        502.0
1000       443.0
1001       171.0
1002       125.0
1004       135.0
1005        12.0
1006        54.0
1007       435.0
1008       135.0
1009       201.0
1010       264.0
1011       420.0
1012       125.0
1013       201.0
1014       226.0
1015       418.0
1016       139.0
1017       201.0
1018       201.0
1019       180.0
1020       179.0
1021       168.0
1022       105.0
1025       135.0
1026       167.0
1027        84.0
1028       144.0
1029       171.0
1030       220.0
1031        84.0
1032       135.0
1033       220.0
1034       135.0
1035       135.0
1036       144.0
1037       149.0
1038       226.0
1039       167.0
1040       125.0
1041       125.0
1042        91.0
1043       226.0
Name: area, dtype: float64

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 992 entries, 0 to 1043
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    992 non-null    object
 1   society          992 non-null    object
 2   price            945 non-null    float64
 3   price_per_sqft   992 non-null    float64
 4   area             992 non-null    float64
 5   areaWithType     945 non-null    object
 6   bedRoom          945 non-null    object
 7   bathroom         945 non-null    object
 8   balcony          945 non-null    object
 9   additionalRoom   566 non-null    object
 10  address          980 non-null    object
 11  noOfFloor        926 non-null    object
 12  facing           648 non-null    object
 13  agePossession    945 non-null    object
 14  nearbyLocations  870 non-null    object
 15  description      985 non-null    object
 16  furnishDetails   715 non-null    object
 17  features         647 non-null    object
 18  rating           861 non-null    object
dtypes: float64(3), object(16)
memory usage: 155.0+ KB

In [19]:
df['bedRoom'].value_counts()

bedRoom
4 Bedrooms     230
5 Bedrooms     183
3 Bedrooms     146
2 Bedrooms      87
6 Bedrooms      80
9 Bedrooms      44
1 Bedroom       38
8 Bedrooms      33
7 Bedrooms      30
12 Bedrooms     27
10 Bedrooms     21
16 Bedrooms     11
13 Bedrooms      4
11 Bedrooms      2
19 Bedrooms      2
18 Bedrooms      2
21 Bedrooms      1
20 Bedrooms      1
36 Bedrooms      1
34 Bedrooms      1
14 Bedrooms      1
Name: count, dtype: int64

In [20]:
df['bedRoom'].unique()

array(['5 Bedrooms', '10 Bedrooms', '21 Bedrooms', '12 Bedrooms',
       '20 Bedrooms', '16 Bedrooms', '6 Bedrooms', '3 Bedrooms',
       '4 Bedrooms', '13 Bedrooms', '9 Bedrooms', '7 Bedrooms',
       '2 Bedrooms', '8 Bedrooms', nan, '1 Bedroom', '18 Bedrooms',
       '19 Bedrooms', '36 Bedrooms', '34 Bedrooms', '14 Bedrooms',
       '11 Bedrooms'], dtype=object)

In [21]:
df.dropna(subset=['bedRoom'],inplace=True)
df['bedRoom'].isnull().sum()
df['bathroom'].isnull().sum()

np.int64(0)

In [22]:
df['bedRoom'] = df['bedRoom'].str.split(" ").str.get(0).astype('int')
df['bedRoom'].value_counts()

bedRoom
4     230
5     183
3     146
2      87
6      80
9      44
1      38
8      33
7      30
12     27
10     21
16     11
13      4
11      2
19      2
18      2
21      1
20      1
36      1
34      1
14      1
Name: count, dtype: int64

In [23]:
df['bathroom'].value_counts()

bathroom
4 Bathrooms     225
3 Bathrooms     164
5 Bathrooms     132
2 Bathrooms     112
6 Bathrooms      82
1 Bathroom       64
9 Bathrooms      41
7 Bathrooms      37
8 Bathrooms      26
12 Bathrooms     21
10 Bathrooms     11
16 Bathrooms      7
13 Bathrooms      4
18 Bathrooms      4
11 Bathrooms      4
17 Bathrooms      3
20 Bathrooms      3
14 Bathrooms      2
21 Bathrooms      1
34 Bathrooms      1
36 Bathrooms      1
Name: count, dtype: int64

In [24]:
df['bathroom'] = df['bathroom'].str.split(" ").str.get(0).astype('int')
df['bathroom'].value_counts()

bathroom
4     225
3     164
5     132
2     112
6      82
1      64
9      41
7      37
8      26
12     21
10     11
16      7
13      4
18      4
11      4
17      3
20      3
14      2
21      1
34      1
36      1
Name: count, dtype: int64

In [25]:
df['balcony'].value_counts()

balcony
3+ Balconies    352
2 Balconies     217
3 Balconies     158
No Balcony      114
1 Balcony       104
Name: count, dtype: int64

In [26]:
# There is a category name 3+ balconies. Thus we can't convert this column to int.
df['balcony'] = df['balcony'].str.split(" ").str.get(0).str.replace('No','0')
df['balcony'].value_counts()

balcony
3+    352
2     217
3     158
0     114
1     104
Name: count, dtype: int64

In [27]:
df['additionalRoom'].isnull().sum()

np.int64(379)

In [28]:
df['additionalRoom'] = df['additionalRoom'].fillna('not available').str.lower()

In [29]:
df['noOfFloor'].unique()

array(['3 Floors', '2 Floors', '5 Floors', '4 Floors', nan, '1 Floors',
       '02 Floors', '14 Floors', '21 Floors', '0 Floors', '12 Floors',
       '27 Floors', '13 Floors', '6 Floors', '10 Floors', '20 Floors',
       '11 Floors', '41 Floors', '51 Floors', '16 Floors', '33 Floors'],
      dtype=object)

In [30]:
df['noOfFloor'] = df['noOfFloor'].str.split(' ').str.get(0)

In [31]:

df.rename(columns={'noOfFloor':'floorNum'},inplace=True)

In [32]:
df['facing'].unique()
df['facing'].fillna('not available',inplace=True)

C:\Users\anush\AppData\Local\Temp\ipykernel_10724\422195418.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['facing'].fillna('not available',inplace=True)

In [33]:
df.insert(loc=1,column='property_type',value='house')

In [34]:
df['society'].value_counts().shape

(171,)

In [35]:
df.shape

(945, 20)

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 945 entries, 0 to 1043
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    945 non-null    object
 1   property_type    945 non-null    object
 2   society          945 non-null    object
 3   price            945 non-null    float64
 4   price_per_sqft   945 non-null    float64
 5   area             945 non-null    float64
 6   areaWithType     945 non-null    object
 7   bedRoom          945 non-null    int64
 8   bathroom         945 non-null    int64
 9   balcony          945 non-null    object
 10  additionalRoom   945 non-null    object
 11  address          940 non-null    object
 12  floorNum         926 non-null    object
 13  facing           945 non-null    object
 14  agePossession    945 non-null    object
 15  nearbyLocations  830 non-null    object
 16  description      945 non-null    object
 17  furnishDetails   715 non-null    object
 18  features         647 non-null    object
 19  rating           825 non-null    object
dtypes: float64(3), int64(2), object(15)
memory usage: 155.0+ KB

In [38]:
df.to_csv('house_cleaned.csv',index=False)