In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [3]:
df = pd.read_csv('flats.csv')
df.shape

(3017, 20)

In [4]:
df.info()  #every column is an object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3017 entries, 0 to 3016
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3017 non-null   object
 1   link             3017 non-null   object
 2   society          3016 non-null   object
 3   price            3007 non-null   object
 4   area             3004 non-null   object
 5   areaWithType     3008 non-null   object
 6   bedRoom          3008 non-null   object
 7   bathroom         3008 non-null   object
 8   balcony          3008 non-null   object
 9   additionalRoom   1694 non-null   object
 10  address          3002 non-null   object
 11  floorNum         3006 non-null   object
 12  facing           2127 non-null   object
 13  agePossession    3007 non-null   object
 14  nearbyLocations  2913 non-null   object
 15  description      3008 non-null   object
 16  furnishDetails   2203 non-null   object
 17  features         2594 non-null   object
 18  rating           2676 non-null   object
 19  property_id      3008 non-null   object
dtypes: object(20)
memory usage: 471.5+ KB

In [6]:
df.sample(6)

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
903,3 BHK Flat in Sector 90 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,DLF Regal Gardens3.9 ★,1.29 Crore,"₹ 9,020/sq.ft.",Super Built up area 1702(158.12 sq.m.)Built Up...,3 Bedrooms,3 Bathrooms,3 Balconies,Study Room,"E174, Sector 90 Gurgaon, Gurgaon, Haryana",7th of 29 Floors,East,1 to 5 Year Old,"['SS Omnia, Sector 86', 'Numberdar market, IMT...",Looking for a 3 bhk property for sale in gurga...,NaN,"['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4.5 out ...",F66607568
2929,3 BHK Flat in Sector 69 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Unitech Sunbreeze,73.53 Lac,"₹ 5,500/sq.ft.",Super Built up area 1337(124.21 sq.m.),3 Bedrooms,3 Bathrooms,1 Balcony,Servant Room,"Sector-69, Gurgaon, Sector 69 Gurgaon, Gurgaon...",10th of 14 Floors,NaN,Under Construction,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",For sale - 3bhk + sr flat measuring 1337sqr ft...,[],"['Power Back-up', 'Intercom Facility', 'Lift(s...","['Safety4 out of 5', 'Lifestyle4 out of 5', 'E...",L24514775
2313,2 BHK Flat in Sohna,https://www.99acres.com/2-bhk-bedroom-apartmen...,GLS Arawali Homes3.8 ★,32 Lac,"₹ 6,722/sq.ft.",Built Up area: 476 (44.22 sq.m.),2 Bedrooms,1 Bathroom,No Balcony,NaN,"Gls Arawali Homes, Sector 4, Gurgaon, Sohna, G...",Ground of 1 Floors,NaN,undefined,"['Huda City Centre', 'Golf Course Road', 'Delh...","Property for sale in sector 4, gurgaon. This 2...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Green Area5 out of 5', 'Construction4 out of...",Y69511686
2477,2 BHK Flat in Sector 63A Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Signature Global City 63A,1.65 Crore,"₹ 15,263/sq.ft.",Super Built up area 1081(100.43 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 63A Gurgaon, Gurgaon, Haryana",1st of 4 Floors,NaN,Oct 2024,"['Sector 54 Chowk Metro Station', 'Paras Trini...",It's a 2bhk in a popular area (Adjoining humon...,"['1 Wardrobe', '1 Fan', '1 Light', '1 AC', 'No...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5...",G69165782
1708,4 BHK Flat in Sector 69 Gurgaon,https://www.99acres.com/4-bhk-bedroom-apartmen...,Tulip Violet4.3 ★,2.05 Crore,"₹ 9,950/sq.ft.",Super Built up area 2087(193.89 sq.m.),4 Bedrooms,4 Bathrooms,2 Balconies,NaN,"003, Sector 69 Gurgaon, Gurgaon, Haryana",Ground of 14 Floors,North-West,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",Ground floor with extended balcony park facing...,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Water purifier', 'Security / Fire Alarm', 'F...","['Green Area5 out of 5', 'Construction4 out of...",N69721252
2158,4 BHK Flat in Cyber City,https://www.99acres.com/4-bhk-bedroom-apartmen...,Dlf 3 Apartment,2.5 Crore,"₹ 7,142/sq.ft.",Super Built up area 3500(325.16 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room","U 27/7, Cyber City, Gurgaon, Haryana",2nd of 2 Floors,North-West,10+ Year Old,"['Vodafone belvedere towers metro station', 'I...",4 master bedroom attached washroom and balconi...,"['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '4 Ge...","['Security Personnel', 'Internet/wi-fi connect...","['Environment5 out of 5', 'Lifestyle5 out of 5...",S69824660

In [ ]:
# Dropping link and prop_id because they are of no use in this analysis
df.drop(columns=['link','property_id'], inplace = True)